### ISSUE TITLE
2 issues on first ng serve

### ISSUE THREAD

**Issue by FriesBureau** [guiseek/ng-fire-calendar#5]
Very fine work by Gui Seek. I've removed my comment.

**Comment by guiseek** [comment]
> Very fine work by Gui Seek. I've removed my comment.

oops. solved? to tell you the truth I had forgotten that this project is here.

In my last project I also needed a calendar and the result was cool. if it is useful for you, I can update the dependency versions of this, then bring the improvements here.

would it be useful @FriesBureau?
